name: Preston
favicon: null
layout_spectrum: 0.53443
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-64365008-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#edefec'
    - '#1d1d1d'
    - '#973e20'
    - '#70726d'
    - '#11a7a6'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
